//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miki1106.WebHandling.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miki1106.WebHandling.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;ERROR {err_num}&lt;/title&gt;
        ///        &lt;style&gt;
        ///            .code-box {
        ///                background-color: #f5f5f5;
        ///                border: 1px solid #ccc;
        ///                padding: 4px;
        ///                font-family: monospace;
        ///                white-space: pre-wrap;
        ///                word-wrap: break-word;
        ///                border-radius: 4px;
        ///            }
        ///            html {
        ///                font-family: cursive;
        ///            }
        ///        &lt;/style&gt;
        ///    &lt;/head&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string error_base {
            get {
                return ResourceManager.GetString("error_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                &lt;tr&gt;
        ///                    &lt;td data-value=&quot;{name}&quot;&gt;
        ///                        &lt;a class=&quot;icon file&quot; draggable=&quot;true&quot; href=&quot;/{path}&quot;&gt;{name}&lt;/a&gt;
        ///                    &lt;/td&gt;
        ///                    &lt;td class=&quot;detailsColumn&quot; data-value=&quot;{size}&quot;&gt;{size_str}&lt;/td&gt;
        ///                    &lt;td class=&quot;detailsColumn&quot; data-value=&quot;{created}&quot;&gt;{created_str}&lt;/td&gt;
        ///                &lt;/tr&gt;.
        /// </summary>
        internal static string item_file {
            get {
                return ResourceManager.GetString("item_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                &lt;tr&gt;
        ///                    &lt;td data-value=&quot;{name}/&quot;&gt;
        ///                        &lt;a class=&quot;icon dir&quot; href=&quot;/{path}&quot;&gt;{name}/&lt;/a&gt;
        ///                    &lt;/td&gt;
        ///                    &lt;td class=&quot;detailsColumn&quot; data-value=&quot;0&quot;&gt;&lt;/td&gt;
        ///                    &lt;td class=&quot;detailsColumn&quot; data-value=&quot;{created}&quot;&gt;{created_str}&lt;/td&gt;
        ///                &lt;/tr&gt;.
        /// </summary>
        internal static string item_folder {
            get {
                return ResourceManager.GetString("item_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html dir=&quot;ltr&quot; lang=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;meta name=&quot;color-scheme&quot; content=&quot;light dark&quot;&gt;
        ///        &lt;meta name=&quot;google&quot; value=&quot;notranslate&quot;&gt;
        ///        &lt;style&gt;
        ///            
        ///            h1 {
        ///                border-bottom: 1px solid #c0c0c0;
        ///                margin-bottom: 10px;
        ///                padding-bottom: 10px;
        ///                white-space: nowrap;
        ///            }
        ///            
        ///            table {
        ///                border-collapse: collapse;
        ///            }
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string static_base {
            get {
                return ResourceManager.GetString("static_base", resourceCulture);
            }
        }
    }
}
